[package]
name = "tableturfer-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.9"
log = "0.4"
config = { version = "0.13.2", features = ["toml"] }
serde = "1.0.147"
