export enum MapSquareType {
    DISABLED = 0,
    EMPTY = 1,
    INACTIVE_SPECIAL_ALPHA = 2,
    INACTIVE_SPECIAL_BRAVO = 3,
    FILL_ALPHA,
    FILL_BRAVO,
    NEUTRAL,
    OUT_OF_BOUNDS,
    ACTIVE_SPECIAL_ALPHA,
    ACTIVE_SPECIAL_BRAVO
}
