export enum MapSquareType {
    DISABLED,
    EMPTY,
    INACTIVE_SPECIAL_ALPHA,
    INACTIVE_SPECIAL_BRAVO,
    FILL_ALPHA,
    FILL_BRAVO,
    NEUTRAL,
    OUT_OF_BOUNDS,
    ACTIVE_SPECIAL_ALPHA,
    ACTIVE_SPECIAL_BRAVO
}
